"use client";
import { useMemo,useState } from "react";
import { treatments } from "../../content/site";
import { preferredDateInfo,waUrl } from "../../lib/business";

export default function AppointmentForm({defaultTreatment=""}){
 const [form,setForm]=useState({name:"",phone:"",treatment:defaultTreatment||"not-sure",date:"",period:"morning",message:""}); const [errors,setErrors]=useState({}); const [fallback,setFallback]=useState("");
 const validateOne=(name,value)=>{let message="";if(name==="name"&&value.trim().length<2)message="Please enter your full name.";if(name==="phone"&&!/^[+\d][\d\s-]{7,17}$/.test(value.trim()))message="Please enter a valid contact number.";if(name==="date"&&value){const d=preferredDateInfo(value);if(!d.valid)message=d.message;}setErrors(prev=>({...prev,[name]:message}));};
 const change=e=>{const {name,value}=e.target;setForm(v=>({...v,[name]:value}));if(name==="date"||errors[name])validateOne(name,value);};
 const minDate=useMemo(()=>{const p=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Kolkata',year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(new Date());const o=Object.fromEntries(p.map(x=>[x.type,x.value]));return `${o.year}-${o.month}-${o.day}`},[]);
 const validate=()=>{const e={};if(form.name.trim().length<2)e.name="Please enter your full name.";if(!/^[+\d][\d\s-]{7,17}$/.test(form.phone.trim()))e.phone="Please enter a valid contact number.";if(!form.date)e.date="Please choose a preferred date.";else{const d=preferredDateInfo(form.date);if(!d.valid)e.date=d.message;}if(!form.treatment)e.treatment="Please choose a treatment or ‘I am not sure yet’.";setErrors(e);return !Object.keys(e).length};
 const submit=e=>{e.preventDefault();setFallback("");if(!validate())return;const label=form.treatment==='not-sure'?'I am not sure yet':treatments.find(t=>t.slug===form.treatment)?.name||form.treatment;const period=form.period==='morning'?'Morning (9:30 am–1:00 pm)':'Afternoon (3:00 pm–6:30 pm)';const msg=`Hello Dental Nation Clinic, I would like to request an appointment.\n\nName: ${form.name.trim()}\nContact: ${form.phone.trim()}\nTreatment: ${label}\nPreferred date: ${form.date}\nPreferred period: ${period}${form.message.trim()?`\nMessage: ${form.message.trim()}`:''}\n\nI understand this is a request and the clinic will confirm availability.`;const url=waUrl(msg);const win=window.open(url,'_blank');if(win)win.opener=null;else setFallback(`WhatsApp did not open. You can copy this request and contact the clinic directly:\n\n${msg}`);};
 return <form className="appointment-form" onSubmit={submit} noValidate><div className="form-note"><strong>Request, not reservation.</strong><span>The clinic confirms availability with you after you send the prepared WhatsApp message.</span></div>
  <div className="form-grid"><Field label="Full name" error={errors.name}><input name="name" value={form.name} onChange={change} onBlur={e=>validateOne("name",e.target.value)} autoComplete="name" required/></Field><Field label="Phone number" error={errors.phone}><input name="phone" value={form.phone} onChange={change} onBlur={e=>validateOne("phone",e.target.value)} inputMode="tel" autoComplete="tel" required/></Field>
  <Field label="Treatment" error={errors.treatment}><select name="treatment" value={form.treatment} onChange={change}><option value="not-sure">I am not sure yet</option>{treatments.map(t=><option key={t.slug} value={t.slug}>{t.name}</option>)}</select></Field><Field label="Preferred date" error={errors.date}><input type="date" name="date" value={form.date} min={minDate} onChange={change} onBlur={e=>validateOne("date",e.target.value)} required/></Field>
  <Field label="Preferred period"><select name="period" value={form.period} onChange={change}><option value="morning">Morning · 9:30 am–1:00 pm</option><option value="afternoon">Afternoon · 3:00 pm–6:30 pm</option></select></Field><Field label="Brief message (optional)" wide><textarea name="message" value={form.message} onChange={change} rows="4" placeholder="Tell us what you have noticed or what you would like help with."/></Field></div>
  <p className="form-micro">Regular hours: Monday–Saturday. Sunday is closed. Preferred date and period are requests only.</p><button className="button button--dark button--wide" type="submit">Prepare request in WhatsApp <span>↗</span></button>{fallback&&<pre className="form-fallback" tabIndex="0">{fallback}</pre>}
 </form>;
}
function Field({label,error,wide=false,children}){return <label className={`field ${wide?'field--wide':''}`}><span>{label}</span>{children}{error&&<em role="alert">{error}</em>}</label>}
