export const sourceUrls = {
  home: "https://www.dentalnationclinic.com/",
  treatments: "https://www.dentalnationclinic.com/services-4",
  contact: "https://www.dentalnationclinic.com/contact-5",
  articles: "https://www.dentalnationclinic.com/blog",
  instagram: "https://www.instagram.com/dentalnationclinic/",
  dolphinRepo: "https://github.com/vauldyyyy/dolphin-aquarium-enhanced",
};

export const business = {
  name: "Dental Nation Clinic",
  shortName: "Dental Nation",
  tagline: "Creating happier smiles.",
  address: "Royal Emerald Complex, Shop no. 5, Bamado, Chinchinim, Goa 403715",
  phoneDisplay: "+91 9270552454",
  phoneE164: "+919270552454",
  whatsappNumber: "919270552454",
  email: "dentalnationclinic@gmail.com",
  timeZone: "Asia/Kolkata",
  hoursLabel: "Monday–Saturday · 9:30 am–1:00 pm · 3:00 pm–6:30 pm",
  openingHours: {
    0: [],
    1: [[570, 780], [900, 1110]],
    2: [[570, 780], [900, 1110]],
    3: [[570, 780], [900, 1110]],
    4: [[570, 780], [900, 1110]],
    5: [[570, 780], [900, 1110]],
    6: [[570, 780], [900, 1110]],
  },
};

export const dentists = [
  {
    slug: "natasha-lopez",
    localOfficial: "/images/team/official/natasha-lopez.jpg",
    name: "Dr. Natasha Lopez",
    credentials: "BDS, FGDS",
    role: "General Dental Surgeon",
    sourceImage: "https://static.wixstatic.com/media/f2a471_dfd3769a1c0d4d5794b2f3308da429cf~mv2.jpg",
    localFallback: "/images/team/natasha-lopez-fallback.svg",
    alt: "Official portrait of Dr. Natasha Lopez",
  },
  {
    slug: "neil-andrade",
    localOfficial: "/images/team/official/neil-andrade.jpg",
    name: "Dr. Neil Andrade",
    credentials: "MDS",
    role: "Orthodontics and Dentofacial Orthopedics",
    sourceImage: "https://static.wixstatic.com/media/f2a471_5b3b1b9dab8241b8a2f663f3c90b54e4~mv2.jpg",
    localFallback: "/images/team/neil-andrade-fallback.svg",
    alt: "Official portrait of Dr. Neil Andrade",
  },
  {
    slug: "yshanna-dsouza",
    localOfficial: "/images/team/official/yshanna-dsouza.jpg",
    name: "Dr. Yshanna D'Souza",
    credentials: "MDS",
    role: "Pedodontist",
    sourceImage: "https://static.wixstatic.com/media/f2a471_68cb350098a34ceabbea34eaacce823d~mv2.jpg",
    localFallback: "/images/team/yshanna-dsouza-fallback.svg",
    alt: "Official portrait of Dr. Yshanna D'Souza",
  },
  {
    slug: "archana-chavan",
    localOfficial: "/images/team/official/archana-chavan.jpg",
    name: "Dr. Archana Chavan",
    credentials: "MDS",
    role: "Endodontist",
    sourceImage: "https://static.wixstatic.com/media/f2a471_68487eb7988748c097e399b280b857a0~mv2.jpg",
    localFallback: "/images/team/archana-chavan-fallback.svg",
    alt: "Official portrait of Dr. Archana Chavan",
  },
];

const commonFaqs = {
  consult: {
    q: "What happens at the consultation?",
    a: "The dentist will ask what is bothering you, examine the relevant teeth and gums, and explain what they can see. If an X-ray or another assessment would add useful information, that is discussed before deciding the next step.",
  },
  suitability: {
    q: "Is this treatment suitable for everyone?",
    a: "Not necessarily. Suitability depends on your oral health, symptoms, medical history and the condition being treated. The dentist will explain appropriate options after an examination.",
  },
  urgency: {
    q: "Should I wait if the problem is not painful?",
    a: "Pain is only one sign of a dental problem. If you notice a change, damage, swelling, bleeding, a lost filling, a loose tooth or another concern, it is sensible to arrange an assessment rather than relying on pain alone.",
  },
};

export const treatmentCategories = [
  { id: "all", label: "All treatments" },
  { id: "everyday", label: "Everyday care" },
  { id: "restore", label: "Repair & restore" },
  { id: "smile", label: "Smile & alignment" },
  { id: "surgical", label: "Surgical care" },
  { id: "family", label: "Family & protection" },
];

export const treatments = [
  {
    slug: "fillings", name: "Fillings", category: "restore", icon: "fillings",
    sourceSummary: "Replacing affected parts of a tooth with tooth-coloured material.",
    intro: "A filling can restore a tooth after decay or minor damage has removed healthy structure.",
    overview: "The dentist first checks how much of the tooth is affected and whether a filling is the right restoration. The damaged or decayed area is cleaned, then the tooth is rebuilt with a restorative material selected for the clinical situation.",
    consultation: "Expect questions about sensitivity, food trapping or discomfort, followed by an examination. An X-ray may be suggested if the extent of decay cannot be judged visually.",
    faqs: [commonFaqs.consult, commonFaqs.suitability, { q: "Will the filling look like my tooth?", a: "Dental Nation's current service description refers to tooth-coloured material. The dentist can explain the material and appearance expected for your particular tooth." }],
    related: ["root-canal-treatment", "crowns-and-bridges", "dental-x-ray"],
  },
  {
    slug: "crowns-and-bridges", name: "Crowns and Bridges", category: "restore", icon: "crown",
    sourceSummary: "Caps for damaged teeth and fixed replacement options for missing teeth.",
    intro: "Crowns protect and rebuild selected damaged teeth; bridges can replace certain missing teeth using fixed restorations.",
    overview: "A crown covers a prepared tooth to restore form and function. A bridge spans a gap and is supported by neighbouring teeth or other planned support. The exact design depends on the condition of the teeth, bite and available support.",
    consultation: "The dentist assesses the tooth or gap, gum health and bite, and discusses whether a crown, bridge or another option is appropriate. Imaging may be used when needed.",
    faqs: [commonFaqs.suitability, { q: "Is a crown always needed after root canal treatment?", a: "Not always. The clinic's existing article notes that teeth often need protection after extensive loss of tooth structure, while options can include crowns or more conservative restorations depending on the tooth." }, commonFaqs.consult],
    related: ["root-canal-treatment", "dental-implants", "dentures-and-partial-dentures"],
  },
  {
    slug: "root-canal-treatment", name: "Root Canal Treatment", category: "restore", icon: "root",
    sourceSummary: "Cleaning and saving a deeply decayed or damaged tooth that might otherwise need removal.",
    intro: "Root canal treatment is used when the soft tissue inside a tooth becomes inflamed or infected and the tooth can be saved.",
    overview: "Treatment focuses on removing infected or inflamed tissue from inside the tooth, cleaning the internal spaces and sealing them. The tooth then needs an appropriate final restoration based on how much structure remains.",
    consultation: "The dentist will review symptoms such as lingering sensitivity, pain on biting or swelling, examine the tooth and usually assess relevant imaging before recommending treatment.",
    faqs: [{ q: "Does every toothache need a root canal?", a: "No. Tooth pain has several possible causes. A clinical examination and, where appropriate, imaging are used to identify the cause before treatment is recommended." }, { q: "Will I need a crown afterwards?", a: "It depends on the tooth and how much healthy structure remains. The clinic's existing article explains that protection is often important, but a crown is not the only possible restoration." }, commonFaqs.suitability],
    related: ["crowns-and-bridges", "dental-x-ray", "extraction"],
  },
  {
    slug: "teeth-cleaning", name: "Teeth Cleaning", category: "everyday", icon: "clean",
    sourceSummary: "Professional cleaning to remove plaque, tartar and stains.",
    intro: "Professional cleaning removes deposits that brushing and flossing cannot always remove at home.",
    overview: "The visit is tailored to what the dentist sees around your teeth and gums. Cleaning may focus on plaque, hardened tartar and surface stains, alongside guidance on maintaining areas that are difficult to reach.",
    consultation: "The dentist checks the gums, areas of buildup and any sensitivity or bleeding before deciding the appropriate cleaning approach.",
    faqs: [{ q: "Is cleaning only cosmetic?", a: "No. Although surface stains may improve, professional cleaning is also part of managing plaque and tartar around teeth and gums." }, { q: "How often should I have my teeth cleaned?", a: "There is no single interval for everyone. Your dentist can recommend a recall based on your gum health, buildup and individual risk factors." }, commonFaqs.consult],
    related: ["gum-treatment", "teeth-whitening", "dental-x-ray"],
  },
  {
    slug: "dentures-and-partial-dentures", name: "Dentures and Partial Dentures", category: "restore", icon: "dentures",
    sourceSummary: "Removable replacement teeth for people who have lost some or all teeth.",
    intro: "Dentures can replace several missing teeth or a full arch of teeth with a removable appliance.",
    overview: "Planning considers the number and position of missing teeth, remaining teeth, gums, bite and how the denture will be supported. The dentist explains the type of denture that may fit your situation and what adjustment period to expect.",
    consultation: "The mouth and remaining teeth are examined, goals and concerns are discussed, and the dentist explains possible removable and fixed alternatives when relevant.",
    faqs: [{ q: "What is the difference between full and partial dentures?", a: "A full denture replaces all teeth in an arch, while a partial denture replaces some missing teeth and works around remaining natural teeth." }, { q: "Are dentures the only way to replace missing teeth?", a: "No. Depending on the case, bridges or dental implants may also be considered. The dentist can explain the differences after assessment." }, commonFaqs.suitability],
    related: ["dental-implants", "crowns-and-bridges", "gum-treatment"],
  },
  {
    slug: "pediatric-dentistry", name: "Pediatric Dentistry", category: "family", icon: "pediatric",
    sourceSummary: "Dental care for children.",
    intro: "Children's dental visits are an opportunity to check development, prevent avoidable problems and help families build comfortable routines.",
    overview: "A child-focused appointment may include a gentle examination, age-appropriate prevention, discussion of brushing and diet, and treatment planning if a problem is found. The pace should suit the child's comfort and needs.",
    consultation: "Parents or carers can share any concerns, previous dental experiences and relevant health information. The dentist then checks the child's teeth and mouth in an age-appropriate way.",
    faqs: [{ q: "When should I bring my child if nothing hurts?", a: "Routine dental checks are useful even without pain because they allow the dentist to review development, hygiene and early changes before they become urgent." }, { q: "What if my child is nervous?", a: "Tell the clinic when booking and at the visit. The team can explain the appointment step by step and adapt the pace to the child." }, commonFaqs.urgency],
    related: ["fillings", "teeth-cleaning", "nightguard-and-mouthguard"],
  },
  {
    slug: "extraction", name: "Extraction", category: "surgical", icon: "extract",
    sourceSummary: "Removal of teeth that are deeply decayed, broken or impacted.",
    intro: "An extraction removes a tooth when keeping it is not appropriate or when removal is part of an agreed treatment plan.",
    overview: "Before removal, the dentist reviews why the tooth is being considered for extraction and whether alternatives exist. The procedure and aftercare depend on the tooth's position, condition and surrounding structures.",
    consultation: "The dentist examines the tooth, reviews relevant health information and may use an X-ray to understand roots and surrounding anatomy before discussing the plan.",
    faqs: [{ q: "Should I eat before a routine extraction?", a: "The clinic's existing article advises patients attending a routine extraction to arrive after eating unless they have been given different instructions for their specific procedure. Always follow the instructions provided for your appointment." }, { q: "What should I plan for after an extraction?", a: "The dentist will give aftercare instructions tailored to the procedure. Ask about eating, cleaning the area, activity and what signs should prompt a call to the clinic." }, commonFaqs.suitability],
    related: ["wisdom-tooth-removal", "dental-x-ray", "dental-implants"],
  },
  {
    slug: "cosmetic-dentistry", name: "Cosmetic Dentistry", category: "smile", icon: "cosmetic",
    sourceSummary: "Care focused on improving the appearance of teeth, gums and smile.",
    intro: "Cosmetic dentistry begins with understanding what you would like to change and whether the teeth and gums are healthy enough for the options being considered.",
    overview: "There is no single cosmetic treatment. Options may involve colour, shape, alignment, replacement of missing teeth or gum appearance. The dentist can explain conservative choices, limitations and maintenance before you decide.",
    consultation: "Bring the specific features you would like to discuss. The dentist will assess oral health, listen to your priorities and explain suitable options without assuming one ideal smile for everyone.",
    faqs: [{ q: "Do cosmetic treatments work the same for everyone?", a: "No. Existing restorations, tooth position, enamel, gum health and individual goals all affect which options are suitable and what changes are realistic." }, { q: "Can I ask for a subtle result?", a: "Yes. The consultation is the place to explain whether you want a small refinement or a more noticeable change, so the discussion can stay aligned with your preferences." }, commonFaqs.suitability],
    related: ["teeth-whitening", "braces-and-aligners", "crowns-and-bridges"],
  },
  {
    slug: "braces-and-aligners", name: "Braces and Aligners", category: "smile", icon: "align",
    sourceSummary: "Correction of teeth that are spaced or crooked.",
    intro: "Orthodontic treatment can move teeth and address selected alignment and bite concerns using braces or aligner systems.",
    overview: "Planning starts with the position of the teeth, the bite and the supporting structures. The orthodontic approach and expected duration vary by case; the dentist or orthodontist explains what is appropriate after assessment.",
    consultation: "Expect an examination of tooth position and bite. Records or imaging may be recommended to plan movement safely and discuss the practical differences between treatment options.",
    faqs: [{ q: "Are clear aligners suitable for every case?", a: "No. Some alignment and bite problems are better treated with other orthodontic approaches. Suitability depends on the individual assessment." }, { q: "Who provides orthodontic care at Dental Nation?", a: "The current clinic team lists Dr. Neil Andrade, MDS, in Orthodontics and Dentofacial Orthopedics." }, commonFaqs.consult],
    related: ["nightguard-and-mouthguard", "cosmetic-dentistry", "teeth-cleaning"],
  },
  {
    slug: "dental-implants", name: "Dental Implants", category: "restore", icon: "implant",
    sourceSummary: "A fixed replacement option for one or multiple missing teeth.",
    intro: "Dental implants can support replacement teeth when a fixed option is clinically appropriate.",
    overview: "Implant planning considers the missing tooth or teeth, gums, available bone, bite, general health and the final restoration. Treatment is staged and the dentist will explain whether additional assessment or specialist input is needed.",
    consultation: "The dentist reviews the gap, surrounding teeth and gums, your health history and any existing imaging. Additional imaging may be recommended before deciding whether implant treatment is appropriate.",
    faqs: [{ q: "Can everyone have an implant?", a: "No. Suitability depends on oral and general health, available support and the specific site. An assessment is needed before recommending implant treatment." }, { q: "Are implants the only fixed option?", a: "Not always. Depending on the case, a bridge may also be considered. The dentist can explain the advantages and limitations of each relevant option." }, commonFaqs.consult],
    related: ["crowns-and-bridges", "dentures-and-partial-dentures", "dental-x-ray"],
  },
  {
    slug: "teeth-whitening", name: "Teeth Whitening", category: "smile", icon: "whitening",
    sourceSummary: "Treatment intended to brighten the colour of natural teeth.",
    intro: "Teeth whitening changes the colour of natural tooth structure and is best planned after checking the health of the teeth and gums.",
    overview: "The dentist can identify whether discolouration is likely to respond to whitening and explain how existing fillings, crowns or other restorations may affect the overall appearance.",
    consultation: "The dentist checks the teeth and gums, asks about sensitivity and previous dental work, and discusses whether whitening is appropriate for your goals.",
    faqs: [{ q: "Will crowns and fillings whiten too?", a: "Dental restorations generally do not change colour in the same way natural teeth do. This is one reason an assessment is useful before whitening." }, { q: "What if my teeth are sensitive?", a: "Mention sensitivity before treatment. The dentist can discuss whether whitening is appropriate and how sensitivity may affect the plan." }, commonFaqs.suitability],
    related: ["teeth-cleaning", "cosmetic-dentistry", "fillings"],
  },
  {
    slug: "wisdom-tooth-removal", name: "Wisdom Tooth Removal", category: "surgical", icon: "wisdom",
    sourceSummary: "Assessment and removal of wisdom teeth that are causing problems such as pain, swelling or infection.",
    intro: "Wisdom teeth do not automatically need removal, but they may need assessment when they are impacted, difficult to clean or associated with repeated problems.",
    overview: "The dentist considers symptoms, position, neighbouring teeth and the surrounding structures. Imaging is commonly useful when deciding whether removal is appropriate and how it should be planned.",
    consultation: "Describe pain, swelling, food trapping, difficulty opening or previous episodes. The dentist examines the area and may recommend an X-ray before discussing monitoring or removal.",
    faqs: [{ q: "Does every wisdom tooth need to come out?", a: "No. Removal is considered when there is a clinical reason. A dentist can explain whether monitoring or treatment is appropriate for your situation." }, { q: "Is this the same as a routine extraction?", a: "Some wisdom teeth are straightforward, while others are more complex because of their position or surrounding anatomy. The assessment determines the appropriate approach." }, commonFaqs.consult],
    related: ["extraction", "dental-x-ray", "gum-treatment"],
  },
  {
    slug: "dental-x-ray", name: "Dental X-Ray", category: "everyday", icon: "xray",
    sourceSummary: "X-rays help the dentist assess teeth and jaw structures that are not fully visible during an examination.",
    intro: "Dental X-rays are diagnostic images used when they add information that cannot be obtained from a visual examination alone.",
    overview: "The type and area imaged depend on the question the dentist is trying to answer—for example, decay between teeth, root shape, bone levels or the position of an unerupted tooth.",
    consultation: "The dentist first decides whether imaging is clinically useful for the issue being assessed and explains what the image is intended to show.",
    faqs: [{ q: "Do I need an X-ray at every visit?", a: "Not necessarily. The need for imaging depends on your dental history, current findings and the clinical question being investigated." }, { q: "Why can an X-ray be useful if the tooth looks normal?", a: "Some areas—such as between teeth, around roots or within the jaw—cannot be fully assessed by looking in the mouth alone." }, commonFaqs.consult],
    related: ["root-canal-treatment", "wisdom-tooth-removal", "dental-implants"],
  },
  {
    slug: "nightguard-and-mouthguard", name: "Nightguard and Mouthguard", category: "family", icon: "guard",
    sourceSummary: "Protective mouth appliances used for night-time grinding or contact sport.",
    intro: "A protective appliance can be planned for specific risks, such as tooth grinding or contact sport.",
    overview: "Nightguards and sports mouthguards have different purposes. The dentist can assess wear, bite and the activity involved, then discuss the type of appliance appropriate for your needs.",
    consultation: "For grinding concerns, the dentist looks for signs of wear and asks about symptoms. For sports protection, the conversation focuses on the activity, fit and practical use.",
    faqs: [{ q: "Is a sports mouthguard the same as a nightguard?", a: "No. They are designed for different types of protection and should be chosen for the intended use." }, { q: "What if I am not sure whether I grind my teeth?", a: "Tell the dentist about jaw tiredness, tooth wear, morning symptoms or anything you have noticed. An examination can help identify relevant signs." }, commonFaqs.suitability],
    related: ["braces-and-aligners", "fillings", "crowns-and-bridges"],
  },
  {
    slug: "gum-treatment", name: "Gum Treatment", category: "everyday", icon: "gum",
    sourceSummary: "Care for gum problems, including deeper cleaning and selected treatments for gum appearance.",
    intro: "Gum treatment starts with identifying why the gums are inflamed, bleeding, receding or otherwise concerning to you.",
    overview: "The current clinic service description includes deep cleaning for swollen gums and selected cosmetic gum procedures. The right approach depends on the diagnosis, gum condition and your goals.",
    consultation: "The dentist checks gum tissues, plaque and tartar levels, bleeding and the support around the teeth. Measurements or imaging may be used when clinically relevant.",
    faqs: [{ q: "Is bleeding when brushing normal?", a: "Bleeding gums can be a sign of inflammation and are worth mentioning at a dental visit, especially if the bleeding is persistent." }, { q: "What is deep cleaning?", a: "Deep cleaning generally refers to cleaning below the gumline when deposits and inflammation extend beyond what a routine clean addresses. The dentist will explain whether that is appropriate for you." }, commonFaqs.consult],
    related: ["teeth-cleaning", "dental-x-ray", "cosmetic-dentistry"],
  },
];

export const practicalFaqs = [
  { q: "Do I need to know which treatment I need before booking?", a: "No. Choose “I am not sure yet” on the appointment form and briefly describe what you have noticed. The dentist can assess the concern before discussing options." },
  { q: "When is Dental Nation open?", a: "The clinic's confirmed regular hours are Monday to Saturday, 9:30 am–1:00 pm and 3:00 pm–6:30 pm. Sunday is closed under the regular schedule. Holiday hours may differ." },
  { q: "What should I bring to my first visit?", a: "Bring any relevant dental records or recent X-rays you already have, a list of medicines or health information the dentist should know, and the questions or concerns you want to discuss." },
  { q: "What if I feel anxious about dental visits?", a: "Tell the clinic when you book and tell the dentist at the start of the visit. The clinic's stated approach is to take concerns seriously, explain what is happening and prioritise patient comfort." },
  { q: "Is my WhatsApp request a confirmed appointment?", a: "No. The website prepares a request for you to send in WhatsApp. The clinic confirms availability with you afterwards." },
  { q: "Can I request morning or afternoon?", a: "Yes. Morning means the clinic's 9:30 am–1:00 pm session, and afternoon means the 3:00 pm–6:30 pm session. Your selection is a preference, not a reserved slot." },
];

export const articles = [
  {
    slug: "what-to-expect-during-a-routine-dental-extraction",
    title: "What to Expect During a Routine Dental Extraction",
    author: "Dr. Natasha Lopez",
    sourceUrl: "https://www.dentalnationclinic.com/post/what-to-expect-during-an-routine-dental-extraction",
    sourceTitle: "What to Expect During an Routine Dental Extraction",
    sourceGrounded: true,
    intro: "Dental extractions can feel intimidating. The clinic's existing article focuses on preparation, understanding the procedure and reducing avoidable anxiety before a routine extraction.",
    sections: [
      { heading: "Before the appointment", body: "The original article advises patients attending a routine extraction to arrive after eating well, unless their dentist has given different instructions for their specific procedure. It also notes that anxiety and an empty stomach can contribute to fainting in susceptible patients." },
      { heading: "Ask what will happen", body: "Before an extraction, the dentist needs to understand the tooth, your symptoms and relevant medical history. You can ask why removal is recommended, whether any alternatives are appropriate, what anaesthesia is planned and what the aftercare will involve." },
      { heading: "Plan for the first hours afterwards", body: "Follow the clinic's personalised instructions on pressure over the socket, eating, cleaning, medicines and activity. Contact the clinic if something feels different from the aftercare guidance you were given." },
    ],
    editorialNote: "The preparation points above are preserved from Dental Nation's existing article. Additional organising text is editorial and is not presented as a new clinical statement by Dr. Lopez.",
  },
  {
    slug: "do-you-really-need-a-crown-after-a-root-canal",
    title: "Do You Really Need a Crown After a Root Canal?",
    author: "Dr. Natasha Lopez",
    sourceUrl: "https://www.dentalnationclinic.com/post/do-you-really-need-a-crown-after-a-root-canal",
    sourceTitle: "Do You Really Need A Crown After a Root Canal?",
    sourceGrounded: true,
    intro: "The clinic's existing article gives a deliberately nuanced answer: a root-canal-treated tooth often needs protection, but that protection is not automatically the same restoration for every tooth.",
    sections: [
      { heading: "Why the tooth may need protection", body: "The source article explains that teeth needing root canal treatment may already have lost substantial structure because of extensive decay or damage. That loss of structure can leave the remaining tooth more vulnerable to fracture." },
      { heading: "A crown is one option, not the only option", body: "The article specifically notes that restorations such as onlays, inlays or vonlays may sometimes be considered as alternatives to a full crown. Which restoration is appropriate depends on the tooth and how much sound structure remains." },
      { heading: "The decision is tooth-specific", body: "A dentist needs to assess the remaining walls, bite, location of the tooth and the final seal before recommending how the tooth should be restored. Ask what is being protected and why a particular restoration is being suggested." },
    ],
    editorialNote: "This page preserves the main position and restoration examples in the existing Dental Nation article; added structure is editorial rather than a new clinician-authored claim.",
  },
  {
    slug: "seven-signs-you-may-need-a-root-canal",
    title: "7 Signs You May Need a Root Canal",
    author: "Dr. Natasha Lopez",
    sourceUrl: "https://www.dentalnationclinic.com/post/do-i-really-need-a-root-canal-7-signs-your-tooth-may-need-one",
    sourceTitle: "7 Signs You May Need an Root Canal",
    sourceGrounded: true,
    intro: "The clinic's existing article starts with the basics: root canal treatment is used when disease reaches the pulp—the soft tissue space inside a tooth containing nerves and blood vessels—and aims to keep a tooth that might otherwise be lost.",
    sections: [
      { heading: "Symptoms need a diagnosis", body: "Possible warning signs can include persistent or lingering tooth pain, sensitivity that does not settle, pain on biting, swelling, a recurring gum swelling, a darkened tooth, or a tooth that has been badly damaged. None of these signs proves that root canal treatment is needed on its own." },
      { heading: "Why an examination matters", body: "The same symptom can have more than one cause. A dentist combines the history of the problem, a clinical examination and, where appropriate, an X-ray before deciding whether the pulp is involved and whether the tooth can be restored." },
      { heading: "Saving the tooth is the aim when appropriate", body: "The source article describes root canal treatment as a way to remove infected pulp tissue, clean the internal space and retain the physical tooth structure when the tooth is otherwise restorable." },
    ],
    editorialNote: "The description of pulp involvement and the tooth-saving purpose are source-grounded. The symptom list is editorial health information and is not presented as a direct quotation or new article authored by Dr. Lopez.",
  },
];

export const galleryRemote = [
  "https://static.wixstatic.com/media/f2a471_7eae0b9dacad4e208c7b847912c455c6~mv2.jpg",
  "https://static.wixstatic.com/media/f2a471_1aa12619473c43bfbf749f5abd6b3726~mv2.jpg",
  "https://static.wixstatic.com/media/f2a471_63713ae36c034bcc8d37c1c17e3bd225~mv2.jpg",
  "https://static.wixstatic.com/media/f2a471_f79886f21836493c8c265b86206986eb~mv2.jpg",
  "https://static.wixstatic.com/media/f2a471_495233e7f4884f66a9af22031540bf75~mv2.jpg",
  "https://static.wixstatic.com/media/f2a471_eedb6a2ea0184c34a38715c801c7a2d1~mv2.jpg",
  "https://static.wixstatic.com/media/f2a471_01deb80cab734117b33bb03b5aec3328~mv2.jpg",
  "https://static.wixstatic.com/media/f2a471_d9720bdf76f944c883e03487589cbe17~mv2.jpg",
  "https://static.wixstatic.com/media/f2a471_3e4cbc54f84d4b399788aaf8456d17f1~mv2.jpg",
  "https://static.wixstatic.com/media/f2a471_524637ad45d844a78abd306769a95ce4~mv2.jpg",
];
